const constants = {
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    SEARCH_ITEM: 'SEARCH_ITEM',
    FILTER_ITEM: 'FILTER_ITEM',
    DONE_ITEM: 'DONE_ITEM',
    IMPORTANT_ITEM: 'IMPORTANT_ITEM',
    FETCH_DATA: 'FETCH_DATA',
    RECEIVE_DATA: 'RECEIVE_DATA',
    DATA_LOADED: 'DATA_LOADED',
    CATCH_ERROR: 'CATCH_ERROR',
};

export default constants;
