const constants = {
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    SEARCH_ITEM: 'SEARCH_ITEM',
    FILTER_ITEM: 'FILTER_ITEM',
    DONE_ITEM: 'DONE_ITEM',
    IMPORTANT_ITEM: 'IMPORTANT_ITEM',
    FETCH_DATA: 'FETCH_DATA',
    RECEIVE_DATA: 'RECEIVE_DATA',
    FETCH_PERSON: 'FETCH_PERSON',
    RECEIVE_PERSON: 'RECEIVE_PERSON',
    ASYNC_PERSON: 'ASYNC_PERSON',
    FETCH_PERSON_FAILED: 'FETCH_PERSON_FAILED',
};

export default constants;
